# Numpy Practice

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [8]:
import numpy as np

arr=np.random.randint(1,21,size=(5,5))
print("Original Array:")
print(arr)

print()

arr[:,2]=1
print("Modified Array:")
print(arr)


Original Array:
[[19 19 20 20 10]
 [ 6 11 10  3  2]
 [ 8 15  3 16  7]
 [12 17  9 11 16]
 [20 10 14 13  8]]

Modified Array:
[[19 19  1 20 10]
 [ 6 11  1  3  2]
 [ 8 15  1 16  7]
 [12 17  1 11 16]
 [20 10  1 13  8]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [20]:
arr=np.arange(1,17).reshape(4,4)
print("Original Array:")
print(arr)

print()

np.fill_diagonal(arr,0)
print("Modified Array:")
print(arr)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Modified Array:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [23]:
arr=np.arange(1,37).reshape(6,6)
print("Original Array:")
print(arr)

print()

print("Sub Arrays:-\n")
print("Third to fifth rows:")
print(arr[3:6])
print()
print("2nd to 4th columns:")
print(arr[:,2:5])
print()
print("3rd to 5th rows and 2nd to 4th columns:")
print(arr[3:6,2:5])


Original Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Sub Arrays:-

Third to fifth rows:
[[19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

2nd to 4th columns:
[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]
 [21 22 23]
 [27 28 29]
 [33 34 35]]

3rd to 5th rows and 2nd to 4th columns:
[[21 22 23]
 [27 28 29]
 [33 34 35]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [30]:
arr=np.random.randint(1,21,size=(5,5))
print("Original Array:\n")
print(arr)

print()
border_array=np.concatenate((arr[0,:],arr[-1,:],arr[:,0],arr[:,-1]))
print("Border Elements array:")
print(border_array)


Original Array:

[[11 14  3 10 20]
 [15 19  7 15  8]
 [20 11  3  2  8]
 [ 5 16 13 12  8]
 [ 4 15  8  2  1]]

Border Elements array:
[11 14  3 10 20  4 15  8  2  1 11 15 20  5  4 20  8  8  8  1]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [34]:
arr1=np.random.randint(1,101,size=(3,4))
arr2=np.random.randint(1,101,size=(3,4))

print(f"Array 1: \n{arr1}\n")
print(f"Array 2: \n{arr2}\n")


print(f"Addition result : \n{arr1+arr2}\n")
print(f"Subtraction result : \n{arr1-arr2}\n")
print(f"Multiplication result : \n{arr1*arr2}\n")
print(f"Division result : \n{arr1/arr2}\n")


Array 1: 
[[88  9 39 57]
 [18 80 30 82]
 [75 50 81 18]]

Array 2: 
[[69 53  3 35]
 [83 98 68 57]
 [46 61 85 10]]

Addition result : 
[[157  62  42  92]
 [101 178  98 139]
 [121 111 166  28]]

Subtraction result : 
[[ 19 -44  36  22]
 [-65 -18 -38  25]
 [ 29 -11  -4   8]]

Multiplication result : 
[[6072  477  117 1995]
 [1494 7840 2040 4674]
 [3450 3050 6885  180]]

Division result : 
[[ 1.27536232  0.16981132 13.          1.62857143]
 [ 0.21686747  0.81632653  0.44117647  1.43859649]
 [ 1.63043478  0.81967213  0.95294118  1.8       ]]



2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [46]:
arr=np.arange(1,17).reshape(4,4)

print(f"Array:\n {arr}")

rows_sum=np.sum(arr,axis=1)
cols_sum=np.sum(arr,axis=0)

print()

print("Rows Sum : ",end='')
print(rows_sum)

print("Columns Sum : ",end='')
print(cols_sum)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Rows Sum : [10 26 42 58]
Columns Sum : [28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [ ]:
arr=np.random.randint(1,101,size=(5,5))

print(f"Array:\n{arr}\n")

print(f"Mean : {np.mean(arr)}")
print(f"Median : {np.median(arr)}")
print(f"Standard Deviation : {np.std(arr)}")
print(f"Variance : {np.var(arr)}")




Array:
[[97 41 34 54 26]
 [51 98  8 52 59]
 [11 18 44 12 81]
 [29 94 23 19 25]
 [39 52 13 44 29]]

Mean : 42.12
Median : 39.0
Standard Deviation : 26.373198516675977
Variance : 695.5455999999999


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [53]:
arr=np.arange(1,10).reshape(3,3)

mean=np.mean(arr)
std=np.std(arr)

normalized_array=(arr-mean)/std
print(f"Normalized Array: \n",normalized_array)

Normalized Array: 
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [ ]:
arr=np.random.randint(1,21,size=(3,3))
print(arr)
arr1=[1,2,3]

print()

new_array=arr+arr1
print(new_array)


[[19  5 11]
 [11 13 19]
 [ 8 12  2]]

[[20  7 14]
 [12 15 22]
 [ 9 14  5]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [61]:
arr1=np.random.randint(1,31,size=(4,4))

arr2=np.random.randint(1,31,size=(4,))

print(f"Arr1 : \n{arr1}\n")
print(f"Arr2 : \n{arr2}\n")

print(f"New Array after broadcasting :\n{arr1-arr2}")


Arr1 : 
[[14 11 22  9]
 [10 26  6 28]
 [ 9 13  8  3]
 [18 23  9 14]]

Arr2 : 
[ 1 12 19  7]

New Array after broadcasting :
[[ 13  -1   3   2]
 [  9  14 -13  21]
 [  8   1 -11  -4]
 [ 17  11 -10   7]]
