# Numpy Practice

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [2]:
import numpy as np

arr=np.random.randint(1,21,size=(5,5))
print("Original Array:")
print(arr)

print()

arr[:,2]=1
print("Modified Array:")
print(arr)


Original Array:
[[ 8 18 11 12 19]
 [17 12  9  1  4]
 [18  4  9  3 14]
 [10 20  7  1  6]
 [11 12  6 10 18]]

Modified Array:
[[ 8 18  1 12 19]
 [17 12  1  1  4]
 [18  4  1  3 14]
 [10 20  1  1  6]
 [11 12  1 10 18]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [3]:
arr=np.arange(1,17).reshape(4,4)
print("Original Array:")
print(arr)

print()

np.fill_diagonal(arr,0)
print("Modified Array:")
print(arr)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Modified Array:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [4]:
arr=np.arange(1,37).reshape(6,6)
print("Original Array:")
print(arr)

print()

print("Sub Arrays:-\n")
print("Third to fifth rows:")
print(arr[3:6])
print()
print("2nd to 4th columns:")
print(arr[:,2:5])
print()
print("3rd to 5th rows and 2nd to 4th columns:")
print(arr[3:6,2:5])


Original Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Sub Arrays:-

Third to fifth rows:
[[19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

2nd to 4th columns:
[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]
 [21 22 23]
 [27 28 29]
 [33 34 35]]

3rd to 5th rows and 2nd to 4th columns:
[[21 22 23]
 [27 28 29]
 [33 34 35]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [5]:
arr=np.random.randint(1,21,size=(5,5))
print("Original Array:\n")
print(arr)

print()
border_array=np.concatenate((arr[0,:],arr[-1,:],arr[:,0],arr[:,-1]))
print("Border Elements array:")
print(border_array)


Original Array:

[[ 6 20  9  1 17]
 [12 20  8 19 14]
 [13 13 13  5  3]
 [14  4 17  7  5]
 [18  5  9 14  5]]

Border Elements array:
[ 6 20  9  1 17 18  5  9 14  5  6 12 13 14 18 17 14  3  5  5]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [6]:
arr1=np.random.randint(1,101,size=(3,4))
arr2=np.random.randint(1,101,size=(3,4))

print(f"Array 1: \n{arr1}\n")
print(f"Array 2: \n{arr2}\n")


print(f"Addition result : \n{arr1+arr2}\n")
print(f"Subtraction result : \n{arr1-arr2}\n")
print(f"Multiplication result : \n{arr1*arr2}\n")
print(f"Division result : \n{arr1/arr2}\n")


Array 1: 
[[96 29 26  2]
 [85 82 47 36]
 [34 54 81 49]]

Array 2: 
[[68 40 29  2]
 [43 56 23  3]
 [81 52 16 21]]

Addition result : 
[[164  69  55   4]
 [128 138  70  39]
 [115 106  97  70]]

Subtraction result : 
[[ 28 -11  -3   0]
 [ 42  26  24  33]
 [-47   2  65  28]]

Multiplication result : 
[[6528 1160  754    4]
 [3655 4592 1081  108]
 [2754 2808 1296 1029]]

Division result : 
[[ 1.41176471  0.725       0.89655172  1.        ]
 [ 1.97674419  1.46428571  2.04347826 12.        ]
 [ 0.41975309  1.03846154  5.0625      2.33333333]]



2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [7]:
arr=np.arange(1,17).reshape(4,4)

print(f"Array:\n {arr}")

rows_sum=np.sum(arr,axis=1)
cols_sum=np.sum(arr,axis=0)

print()

print("Rows Sum : ",end='')
print(rows_sum)

print("Columns Sum : ",end='')
print(cols_sum)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Rows Sum : [10 26 42 58]
Columns Sum : [28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [8]:
arr=np.random.randint(1,101,size=(5,5))

print(f"Array:\n{arr}\n")

print(f"Mean : {np.mean(arr)}")
print(f"Median : {np.median(arr)}")
print(f"Standard Deviation : {np.std(arr)}")
print(f"Variance : {np.var(arr)}")




Array:
[[ 1 33 84 73 71]
 [32 23 37 44 54]
 [ 8 54 70 18 69]
 [62 91 70 39 48]
 [24 41 80 53 10]]

Mean : 47.56
Median : 48.0
Standard Deviation : 24.59443839570239
Variance : 604.8864


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [9]:
arr=np.arange(1,10).reshape(3,3)

mean=np.mean(arr)
std=np.std(arr)

normalized_array=(arr-mean)/std
print(f"Normalized Array: \n",normalized_array)

Normalized Array: 
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [10]:
arr=np.random.randint(1,21,size=(3,3))
print(arr)
arr1=[1,2,3]

print()

new_array=arr+arr1
print(new_array)


[[14 14  6]
 [16 10  9]
 [19 13 17]]

[[15 16  9]
 [17 12 12]
 [20 15 20]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [11]:
arr1=np.random.randint(1,31,size=(4,4))

arr2=np.random.randint(1,31,size=(4,))

print(f"Arr1 : \n{arr1}\n")
print(f"Arr2 : \n{arr2}\n")

print(f"New Array after broadcasting :\n{arr1-arr2}")


Arr1 : 
[[30 16 14 17]
 [ 2  7 25 13]
 [10  3 21  6]
 [23 26 20 27]]

Arr2 : 
[25 12 15 17]

New Array after broadcasting :
[[  5   4  -1   0]
 [-23  -5  10  -4]
 [-15  -9   6 -11]
 [ -2  14   5  10]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [14]:
matrix=np.random.randint(1,13,size=(3,3))

print("Matrix:")
print(matrix)

print()

determinant=np.linalg.det(matrix)
inverse=np.linalg.inv(matrix)
eigen_values=np.linalg.eigvals(matrix)



print("Determinant:",determinant,"\n")
print("Inverse Matrix:\n",inverse,"\n")
print("Eigen Values:",eigen_values,"\n")



Matrix:
[[ 2 12  8]
 [10  1  4]
 [ 2 12  9]]

Determinant: -118.00000000000004 

Inverse Matrix:
 [[ 0.33050847  0.10169492 -0.33898305]
 [ 0.69491525 -0.01694915 -0.61016949]
 [-1.          0.          1.        ]] 

Eigen Values: [-8.32396379  0.72323529 19.6007285 ] 



2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [16]:
m1=np.random.randint(1,11,size=(2,3))
m2=np.random.randint(1,11,size=(3,2))

print(f"Matrix 1: \n{m1}\nMatrix 2: \n{m2}")

result=np.matmul(m1,m2)
print("Matrix Multiplication  Result:\n",result)


Matrix 1: 
[[4 7 8]
 [6 6 9]]
Matrix 2: 
[[4 7]
 [8 6]
 [8 3]]
Matrix Multiplication  Result:
 [[136  94]
 [144 105]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [18]:
arr1=np.arange(1,10).reshape((3,3))
arr2=arr1.reshape((1,9))
arr3=arr2.reshape((9,1))

print(arr3)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [21]:
arr=np.random.randint(1,31,size=(5,5))
print(f"Array:\n{arr}")
flattened_array=arr.flatten()
print(f"Flattened Array:\n{flattened_array}")
arr1=flattened_array.reshape((5,5))
print("Reshaped array:\n",arr1)

Array:
[[19 22 23 12 27]
 [30 15 12 12 20]
 [ 3  8 14  1 15]
 [17 19 21 21 16]
 [14 12  4  6 23]]
Flattened Array:
[19 22 23 12 27 30 15 12 12 20  3  8 14  1 15 17 19 21 21 16 14 12  4  6
 23]
Reshaped array:
 [[19 22 23 12 27]
 [30 15 12 12 20]
 [ 3  8 14  1 15]
 [17 19 21 21 16]
 [14 12  4  6 23]]
