# Numpy Practice

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [2]:
import numpy as np

arr=np.random.randint(1,21,size=(5,5))
print("Original Array:")
print(arr)

print()

arr[:,2]=1
print("Modified Array:")
print(arr)


Original Array:
[[20  7 14 19  7]
 [20 15  6 14  7]
 [ 9  1  4 13  7]
 [ 9 10  8 20  3]
 [17  7  4 13 19]]

Modified Array:
[[20  7  1 19  7]
 [20 15  1 14  7]
 [ 9  1  1 13  7]
 [ 9 10  1 20  3]
 [17  7  1 13 19]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [3]:
arr=np.arange(1,17).reshape(4,4)
print("Original Array:")
print(arr)

print()

np.fill_diagonal(arr,0)
print("Modified Array:")
print(arr)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Modified Array:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [4]:
arr=np.arange(1,37).reshape(6,6)
print("Original Array:")
print(arr)

print()

print("Sub Arrays:-\n")
print("Third to fifth rows:")
print(arr[3:6])
print()
print("2nd to 4th columns:")
print(arr[:,2:5])
print()
print("3rd to 5th rows and 2nd to 4th columns:")
print(arr[3:6,2:5])


Original Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Sub Arrays:-

Third to fifth rows:
[[19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

2nd to 4th columns:
[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]
 [21 22 23]
 [27 28 29]
 [33 34 35]]

3rd to 5th rows and 2nd to 4th columns:
[[21 22 23]
 [27 28 29]
 [33 34 35]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [5]:
arr=np.random.randint(1,21,size=(5,5))
print("Original Array:\n")
print(arr)

print()
border_array=np.concatenate((arr[0,:],arr[-1,:],arr[:,0],arr[:,-1]))
print("Border Elements array:")
print(border_array)


Original Array:

[[16  1 15 20 12]
 [ 5  4 13  5 13]
 [ 9  3 16 10 14]
 [16  6  5 19 15]
 [ 5 17 16  2  9]]

Border Elements array:
[16  1 15 20 12  5 17 16  2  9 16  5  9 16  5 12 13 14 15  9]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [6]:
arr1=np.random.randint(1,101,size=(3,4))
arr2=np.random.randint(1,101,size=(3,4))

print(f"Array 1: \n{arr1}\n")
print(f"Array 2: \n{arr2}\n")


print(f"Addition result : \n{arr1+arr2}\n")
print(f"Subtraction result : \n{arr1-arr2}\n")
print(f"Multiplication result : \n{arr1*arr2}\n")
print(f"Division result : \n{arr1/arr2}\n")


Array 1: 
[[24 56 18  2]
 [82 30 41  1]
 [48 61 27 97]]

Array 2: 
[[49 56  1 31]
 [63 61 62 58]
 [58 60 48 38]]

Addition result : 
[[ 73 112  19  33]
 [145  91 103  59]
 [106 121  75 135]]

Subtraction result : 
[[-25   0  17 -29]
 [ 19 -31 -21 -57]
 [-10   1 -21  59]]

Multiplication result : 
[[1176 3136   18   62]
 [5166 1830 2542   58]
 [2784 3660 1296 3686]]

Division result : 
[[4.89795918e-01 1.00000000e+00 1.80000000e+01 6.45161290e-02]
 [1.30158730e+00 4.91803279e-01 6.61290323e-01 1.72413793e-02]
 [8.27586207e-01 1.01666667e+00 5.62500000e-01 2.55263158e+00]]



2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [7]:
arr=np.arange(1,17).reshape(4,4)

print(f"Array:\n {arr}")

rows_sum=np.sum(arr,axis=1)
cols_sum=np.sum(arr,axis=0)

print()

print("Rows Sum : ",end='')
print(rows_sum)

print("Columns Sum : ",end='')
print(cols_sum)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Rows Sum : [10 26 42 58]
Columns Sum : [28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [8]:
arr=np.random.randint(1,101,size=(5,5))

print(f"Array:\n{arr}\n")

print(f"Mean : {np.mean(arr)}")
print(f"Median : {np.median(arr)}")
print(f"Standard Deviation : {np.std(arr)}")
print(f"Variance : {np.var(arr)}")




Array:
[[27 31 80 13 80]
 [67 72 55 41 34]
 [39 76 86 38 43]
 [79 92 91 37 59]
 [42 30 28 33  6]]

Mean : 51.16
Median : 42.0
Standard Deviation : 24.621421567407516
Variance : 606.2144000000001


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [9]:
arr=np.arange(1,10).reshape(3,3)

mean=np.mean(arr)
std=np.std(arr)

normalized_array=(arr-mean)/std
print(f"Normalized Array: \n",normalized_array)

Normalized Array: 
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [10]:
arr=np.random.randint(1,21,size=(3,3))
print(arr)
arr1=[1,2,3]

print()

new_array=arr+arr1
print(new_array)


[[13  2  2]
 [ 8 16  2]
 [10  1  2]]

[[14  4  5]
 [ 9 18  5]
 [11  3  5]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [11]:
arr1=np.random.randint(1,31,size=(4,4))

arr2=np.random.randint(1,31,size=(4,))

print(f"Arr1 : \n{arr1}\n")
print(f"Arr2 : \n{arr2}\n")

print(f"New Array after broadcasting :\n{arr1-arr2}")


Arr1 : 
[[17 15  8 16]
 [23 23 20  9]
 [24 16  8 10]
 [19 10 29  5]]

Arr2 : 
[12  4 12 21]

New Array after broadcasting :
[[  5  11  -4  -5]
 [ 11  19   8 -12]
 [ 12  12  -4 -11]
 [  7   6  17 -16]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [12]:
matrix=np.random.randint(1,13,size=(3,3))

print("Matrix:")
print(matrix)

print()

determinant=np.linalg.det(matrix)
inverse=np.linalg.inv(matrix)
eigen_values=np.linalg.eigvals(matrix)



print("Determinant:",determinant,"\n")
print("Inverse Matrix:\n",inverse,"\n")
print("Eigen Values:",eigen_values,"\n")



Matrix:
[[ 8  7 12]
 [ 9  2 10]
 [ 1 11 11]]

Determinant: -163.00000000000014 

Inverse Matrix:
 [[ 0.5398773  -0.33742331 -0.28220859]
 [ 0.54601227 -0.46625767 -0.17177914]
 [-0.59509202  0.49693252  0.28834356]] 

Eigen Values: [-3.99362202  1.75645692 23.23716511] 



2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [13]:
m1=np.random.randint(1,11,size=(2,3))
m2=np.random.randint(1,11,size=(3,2))

print(f"Matrix 1: \n{m1}\nMatrix 2: \n{m2}")

result=np.matmul(m1,m2)
print("Matrix Multiplication  Result:\n",result)


Matrix 1: 
[[1 2 5]
 [7 2 2]]
Matrix 2: 
[[ 9  3]
 [ 7  6]
 [10  3]]
Matrix Multiplication  Result:
 [[73 30]
 [97 39]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [14]:
arr1=np.arange(1,10).reshape((3,3))
arr2=arr1.reshape((1,9))
arr3=arr2.reshape((9,1))

print(arr3)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [15]:
arr=np.random.randint(1,31,size=(5,5))
print(f"Array:\n{arr}")
flattened_array=arr.flatten()
print(f"Flattened Array:\n{flattened_array}")
arr1=flattened_array.reshape((5,5))
print("Reshaped array:\n",arr1)

Array:
[[25 15 29 19 24]
 [ 8 27  9  4 13]
 [17 25  1 10 29]
 [ 8  6 27 25  7]
 [ 3 17  6 21  4]]
Flattened Array:
[25 15 29 19 24  8 27  9  4 13 17 25  1 10 29  8  6 27 25  7  3 17  6 21
  4]
Reshaped array:
 [[25 15 29 19 24]
 [ 8 27  9  4 13]
 [17 25  1 10 29]
 [ 8  6 27 25  7]
 [ 3 17  6 21  4]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [25]:
arr=np.random.randint(1,21,size=(5,5))
corner_arr= arr[[0, 0, -1, -1], [0, -1, 0, -1]]
print(arr)
print()
print(corner_arr)


[[ 3 15 20  5 14]
 [ 9 11 11 10  6]
 [16  7  3  3 11]
 [ 1  5  8  4 14]
 [16 19  4 19  5]]

[ 3 14 16  5]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [18]:
arr=np.random.randint(1,31,size=(4,4))
print(arr)
print()
arr[arr > 10]=10
print(arr)

[[28 30  5 19]
 [12 25  1 23]
 [30  2  6 25]
 [12  2 20  3]]

[[10 10  5 10]
 [10 10  1 10]
 [10  2  6 10]
 [10  2 10  3]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [ ]:
data_type=[('name', 'U100'), ('age', 'i4'), ('weight', 'f4')]
data=np.array([('Mahendra Singh Dhoni',44, 55.5), ('Parth Gupta',18,49.3), ('Virat Kohli',37,65.2)], dtype=data_type)
print("Original array:")
print(data)

sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Mahendra Singh Dhoni', 44, 55.5) ('Parth Gupta', 18, 85.3)
 ('Virat Kohli', 37, 65.2)]
Sorted array by age:
[('Parth Gupta', 18, 85.3) ('Virat Kohli', 37, 65.2)
 ('Mahendra Singh Dhoni', 44, 55.5)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [37]:
data_types=[('x','i8'),('y','i8')]
data=np.array([(1,2),(3,4),(5,6),(7,8)],dtype=data_types)
print(arr)
print()
distances=np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean Distances:\n",distances)

[(1, 2) (3, 4) (5, 6) (7, 8)]

Euclidean Distances:
 [[0.         2.82842712 5.65685425 8.48528137]
 [2.82842712 0.         2.82842712 5.65685425]
 [5.65685425 2.82842712 0.         2.82842712]
 [8.48528137 5.65685425 2.82842712 0.        ]]
